name: comigean
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - hmmer
  - prodigal
  - biopython
  - muscle
  - fasttree
  - fastani
  - pip:
    - argh
    - pandas
    - wget
    - docopt
    - Jinja2
    - matplotlib
